### ISSUE TITLE
input in python 2

### ISSUE THREAD

**Issue by rnc** [letorbi/synoindexwatcher#40]
While the readme says its python 2/3 compatible in https://github.com/letorbi/synoindexwatcher/blob/master/synoindexwatcher/__main__.py#L175 it uses input - for python 2 I think it would be better to use raw_input (and input for python 3). This avoids strange errors when parsing.

See
https://stackoverflow.com/questions/4960208/python-2-7-getting-user-input-and-manipulating-as-string-without-quotations
https://stackoverflow.com/questions/5074225/python-unexpected-eof-while-parsing

**Comment by Giannie** [comment]
See my PR for a potential simple fix (with the downside of an added dependency).

**Comment by letorbi** [comment]
First of all thanks for reporting the issue and sorry for the late answer. I didn't have the time to answer earlier.

I'm actually wondering for some time now, if it make sense to have the whole `--rebuild-index` functionality (this is where the `input()` call happens) inside Synoindex Watcher. Especially the meddling with the database seems to be out-of-scope for me, since Synoindex Watcher is more about watching files and not about managing the media index. It just doesn't seem to be in line with [the Unix philosophy](https://nymity.ch/sybilhunting/pdf/Pike1983a.pdf).

Regarding this, I tend to "fix" the bug simply by changing the `--rebuild-index` functionality. The SQL-commands to clear the media-index in the database will be removed from the code, but I will create a FAQ entry that describes how the index can be cleared manually. Afterwards the `--rebuild-index` option will only ensure that all files of the watched folders will be added to the media-index once when Synoindex Watcher is started.

This would remove the need for a user-confirmation and thus the `input()` call as well.

I'll leave this issue open for some more days, to give you the chance to convince me to keep the current rebuild-index functionality.

**Comment by rnc** [comment]
Hi, thanks for the considered reply. This is an interesting viewpoint especially from my point of view with my current issues with Synology media indexing and photo station - their application appears to operate and detect kernel level bind mount meaning it doesn't work correctly with mounted folders to e.g. the CloudStation. Apparently in DSM 7 I have been informed by support it will get even stricter completely prohibiting the mounted folder.  For now at least with DSM 6 being able to force the media indexing is useful. Perhaps one option might be to spawn it off into a separate tool?

**Comment by letorbi** [comment]
I think you've misunderstood my previous answer, @rnc.

I'm not planning to remove the media indexing functionality itself from Synoindex Watcher. It will still call `synoindex` to update the media-index (like it does now), if a file or directory has been created or deleted. I just want so remove the code that clears the whole media-index in the database, when Synoindex-Watcher has been called with the `--rebuild-index` option. I've edited my previous answer to make this a bit clearer.

If I understand your use-case correctly, you should not be affected, when I remove the index-clearing-functionality. Or am I missing something?

**Comment by letorbi** [comment]
PS: One might argue that Synoindex Watcher should actually be splitted into two tools to follow the Unix philosophy, but that's a totally different issue ;)
