### ISSUE TITLE
Check whether watched path exists

### ISSUE THREAD

**Issue by mick-pihole** [letorbi/synoindexwatcher#44]
`root@HomdeDS:~# /usr/local/etc/rc.d/S99synoindexwatcher.sh stop
Stopping synoindexwatcher...
/usr/local/etc/rc.d/S99synoindexwatcher.sh: line 24: kill: (12506) - No such process
root@HomdeDS:~# /usr/local/etc/rc.d/S99synoindexwatcher.sh start
Starting synoindexwatcher...
root@HomdeDS:~# /usr/local/etc/rc.d/S99synoindexwatcher.sh stop
Stopping synoindexwatcher...
/usr/local/etc/rc.d/S99synoindexwatcher.sh: line 24: kill: (19188) - No such process
root@HomdeDS:~# ls /usr/local/etc/rc.d
S99synoindexwatcher.sh
root@HomdeDS:~#`

**Comment by mick-pihole** [comment]
found issue: forder  /volume1/photo not exist.  caused the script crash.
hope script will automatic  ingnore such forder.

**Comment by letorbi** [comment]
Thanks for the feedback. Will add an is-existing check for implicitly used folders ( /volume1/music,  /volume1/photo,  /volume1/video).

I won't add a check for explicitly used folders (added via command-line or config-file), because IMHO the user should be notified in case he/she made a typo.

**Comment by letorbi** [comment]
Commit 36a8fbf8147b2ad37c4ac22c67e331f106b8ae01 adds a clearer error message along with an explanation and an example how to fix the problem, if an implicitly watched path does not exist. This think this is enough.

IMHO silently skipping an implicitly watched folder, if it doesn't exist, could cause more confusion than it helps, because people might be irritated, why a path like */volume1/Music* won't be watched.
