### ISSUE TITLE
Error...

### ISSUE THREAD

**Issue by NelsonBarata** [letorbi/synoindexwatcher#48]
While trying your script on a DS211j (python 2.7), I got the following error when executing with a path as a parameter:

2021-05-04 08:46:08,811 ERROR An uncaught exception occurred
Traceback (most recent call last):
  File "/lib/python2.7/site-packages/synoindexwatcher/__main__.py", line 218, in <module>
    start()
  File "/lib/python2.7/site-packages/synoindexwatcher/__main__.py", line 183, in start
    inotify = INotify()
  File "/usr/lib/python2.7/site-packages/inotifyrecursive/inotifyrecursive.py", line 31, in __init__
    inotify_simple.INotify.__init__(self)
  File "/usr/lib/python2.7/site-packages/inotify_simple.py", line 91, in __init__
    FileIO.__init__(self, _libc_call(_libc.inotify_init1, flags), mode='rb')
IOError: [Errno 21] Is a directory: 3

**Comment by letorbi** [comment]
Hej Nelson,

sorry for being so late with a reponse. Could you give me the complete command-line call you've used to start Synoindex Watcher, when this error occurred?

Regards,
Torben

**Comment by letorbi** [comment]
It would also be great to know what DSM version you are running.

**Comment by letorbi** [comment]
Since the exception comes from code, which is part of the *inotify_simple* module, I've created an issue there to ask the developer about his opinion.

**Comment by letorbi** [comment]
According to the developer of *inotify_simple* the minimum required kernel is 3.0.0. Using it with older kernels produces exactly the error you have reported, so I assume this is the origin of you problem as well.

I won't fix Synoindex Watcher to support older kernel versions, since 3.0.0. is quite old already. However, *inotify_simple* 1.2.1 support older kernels, so you could try to install *synindexwatcher* 0.10.0 and force *inotifyrecursive* to version 0.3.0 and *inotify_simple* to 1.2.1. Or you upgrade your system, which might be the better idea ;)

I'm closing this issue now, but please re-open it, if you are using a kernel above or equal to version 3.0.0.

**Comment by NelsonBarata** [comment]
Hi, thansk for your reply.
Indeed, I am using a DSM 5.2 (kernel 2.6.32.12) on a 211j server. This is
the best version I can use on this system.
I 'll try to downgrade the Synoindex Watcher sometime, I'll tell you if it
works.

Best regards,

Nelson.

**Comment by gitraphha** [comment]
Hey letorbi and everyone,
I ran into the same issue with a slightly different setting, see below

Upgrading my system is not possible since it's too old...
But your solution as propsed in [this comment](https://github.com/letorbi/synoindexwatcher/issues/48#issuecomment-850242300) (downgrading all packages) worked very well with some small testcases.
Will have to do make do with not enjoying all the later bugfixes and improvements

many thanks anyways for finding this workaround for us "oldtimers"!

```
My setup:
# python3 -V
Python 3.8.6

# more /etc.defaults/VERSION
majorversion="6"
minorversion="2"
major="6"
minor="2"
micro="4"
productversion="6.2.4"
buildphase="GM"
buildnumber="25556"
smallfixnumber="2"
nano="0"
base="25556"
builddate="2021/08/28"
buildtime="19:23:18"

# uname -a
Linux Host42 2.6.32.12 #25556 SMP Thu Jul 1 14:30:01 CST 2021 ppc GNU/Linux synology_qoriq_213+

# cat synoindexwatcher.log
Traceback (most recent call last):
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/synoindexwatcher/__main__.py", line 224, in <module>
    start()
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/synoindexwatcher/__main__.py", line 189, in start
    inotify = INotify()
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/inotifyrecursive/inotifyrecursive.py", line 31, in __init__
    inotify_simple.INotify.__init__(self)
  File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/inotify_simple.py", line 94, in __init__
    FileIO.__init__(self, _libc_call(_libc.inotify_init1, flags), mode='rb')
IsADirectoryError: [Errno 21] Is a directory: 5

```
